data_dir: $CCL2022_CGED-8_Top1_project/dataset/
exp_dir: $CCL2022_CGED-8_Top1_project/Grammar_Error_Correct/Pointer-Generator-Net/output/
model_name: $bart_chinese_large目录
task_name: 'Grammar_correct_task_predict_22'
skip_train: 1
# 预测时需要加载的模型
resume_model_path: $待预测的模型地址
beam_k: 3
train_file_name: train.jsonl
dev_file_name: dev.jsonl
test_file_name: cged2022/cged2022-test.jsonl
load_test: 1
dropout: 0.1
max_seq_len: 256
train_batch_size: 128
eval_batch_size: 64
learning_rate: 1e-5
num_train_epochs: 10
no_cuda: False
# specify the GPU number
cuda_device: '0'
seed: 99
gradient_accumulation_steps: 1
over_write_cache: 1
resume_latest_cpt: 1
bad_case: 0
# save_cpt_flag value: {0: only save best model; 1: save best model & last epoch model; 2: save best model & each epoch model}
save_cpt_flag: 1
percent: 1.0